# RetailPulse Inventory Optimization

## Business Objective

Optimize inventory levels and identify reorder requirements using SKU demand patterns.

In [5]:
import pandas as pd

df = pd.read_csv(
    "../data/dataset_3_sku_level_inventory_forecasting.csv.csv"
)

df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/dataset_3_sku_level_inventory_forecasting.csv.csv'

In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv(
    "../data/dataset_3_sku_level_inventory_forecasting.csv"
)

df.head()

,StockCode,Description,Total_Quantity_Sold,Total_Revenue,Avg_Price,First_Sale_Date,Last_Sale_Date,Num_Orders,Num_Countries_Sold,SKU_Demand_Velocity,Return_Rate,Average_Daily_Demand,Gross_Quantity,Return_Quantity,Net_Quantity,Product_Lifespan_Days
0,10002,INFLATABLE POLITICAL GLOBE,8671,6942.26,0.979155,2009-12-01,2011-04-18,362,12,38.537778,0.135693,17.204365,9013.0,1223.0,7790.0,504
1,10080,GROOVY CACTUS INFLATABLE,315,129.29,0.505000,2009-12-02,2011-11-21,27,1,12.115385,0.000000,0.437500,597.0,0.0,597.0,720
2,10109,BENDY COLOUR PENCILS,4,1.68,0.420000,2009-12-03,2009-12-03,1,1,4.000000,0.000000,4.000000,0.0,0.0,0.0,1
3,10120,DOGGY RUBBER,664,142.74,0.240137,2009-12-01,2011-12-04,73,2,10.375000,-0.003606,0.904632,-8320.0,30.0,-8350.0,734
4,10125,MINI FUNKY DESIGN TAPES,2103,1715.78,0.930636,2009-12-01,2011-12-09,167,6,16.959677,0.000000,2.845737,2151.0,0.0,2151.0,739

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4917 entries, 0 to 4916
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   StockCode              4917 non-null   str
 1   Description            4917 non-null   str
 2   Total_Quantity_Sold    4917 non-null   int64
 3   Total_Revenue          4917 non-null   float64
 4   Avg_Price              4917 non-null   float64
 5   First_Sale_Date        4917 non-null   str
 6   Last_Sale_Date         4917 non-null   str
 7   Num_Orders             4917 non-null   int64
 8   Num_Countries_Sold     4917 non-null   int64
 9   SKU_Demand_Velocity    4917 non-null   float64
 10  Return_Rate            4917 non-null   float64
 11  Average_Daily_Demand   4917 non-null   float64
 12  Gross_Quantity         4917 non-null   float64
 13  Return_Quantity        4917 non-null   float64
 14  Net_Quantity           4917 non-null   float64
 15  Product_Lifespan_Days  4917 non-null   int64
dtypes: float64(8), int64(4), str(4)
memory usage: 614.8 KB

In [9]:
df.columns

Index(['StockCode', 'Description', 'Total_Quantity_Sold', 'Total_Revenue',
       'Avg_Price', 'First_Sale_Date', 'Last_Sale_Date', 'Num_Orders',
       'Num_Countries_Sold', 'SKU_Demand_Velocity', 'Return_Rate',
       'Average_Daily_Demand', 'Gross_Quantity', 'Return_Quantity',
       'Net_Quantity', 'Product_Lifespan_Days'],
      dtype='str')

In [11]:
import pandas as pd

df = pd.read_csv(
    "../data/dataset_3_sku_level_inventory_forecasting.csv"
)

df.head()

,StockCode,Description,Total_Quantity_Sold,Total_Revenue,Avg_Price,First_Sale_Date,Last_Sale_Date,Num_Orders,Num_Countries_Sold,SKU_Demand_Velocity,Return_Rate,Average_Daily_Demand,Gross_Quantity,Return_Quantity,Net_Quantity,Product_Lifespan_Days
0,10002,INFLATABLE POLITICAL GLOBE,8671,6942.26,0.979155,2009-12-01,2011-04-18,362,12,38.537778,0.135693,17.204365,9013.0,1223.0,7790.0,504
1,10080,GROOVY CACTUS INFLATABLE,315,129.29,0.505000,2009-12-02,2011-11-21,27,1,12.115385,0.000000,0.437500,597.0,0.0,597.0,720
2,10109,BENDY COLOUR PENCILS,4,1.68,0.420000,2009-12-03,2009-12-03,1,1,4.000000,0.000000,4.000000,0.0,0.0,0.0,1
3,10120,DOGGY RUBBER,664,142.74,0.240137,2009-12-01,2011-12-04,73,2,10.375000,-0.003606,0.904632,-8320.0,30.0,-8350.0,734
4,10125,MINI FUNKY DESIGN TAPES,2103,1715.78,0.930636,2009-12-01,2011-12-09,167,6,16.959677,0.000000,2.845737,2151.0,0.0,2151.0,739

In [12]:
print(df.columns.tolist())

['StockCode', 'Description', 'Total_Quantity_Sold', 'Total_Revenue', 'Avg_Price', 'First_Sale_Date', 'Last_Sale_Date', 'Num_Orders', 'Num_Countries_Sold', 'SKU_Demand_Velocity', 'Return_Rate', 'Average_Daily_Demand', 'Gross_Quantity', 'Return_Quantity', 'Net_Quantity', 'Product_Lifespan_Days']

In [14]:
inventory_df = df.copy()

inventory_df["Safety_Stock"] = (
    inventory_df["Average_Daily_Demand"] * 7
)

inventory_df["Reorder_Point"] = (
    inventory_df["Average_Daily_Demand"] * 14
)

inventory_df["Inventory_Gap"] = (
    inventory_df["Reorder_Point"]
    - inventory_df["Net_Quantity"]
)

inventory_df.head()

,StockCode,Description,Total_Quantity_Sold,Total_Revenue,Avg_Price,First_Sale_Date,Last_Sale_Date,Num_Orders,Num_Countries_Sold,SKU_Demand_Velocity,Return_Rate,Average_Daily_Demand,Gross_Quantity,Return_Quantity,Net_Quantity,Product_Lifespan_Days,Safety_Stock,Reorder_Point,Inventory_Gap
0,10002,INFLATABLE POLITICAL GLOBE,8671,6942.26,0.979155,2009-12-01,2011-04-18,362,12,38.537778,0.135693,17.204365,9013.0,1223.0,7790.0,504,120.430556,240.861111,-7549.138889
1,10080,GROOVY CACTUS INFLATABLE,315,129.29,0.505000,2009-12-02,2011-11-21,27,1,12.115385,0.000000,0.437500,597.0,0.0,597.0,720,3.062500,6.125000,-590.875000
2,10109,BENDY COLOUR PENCILS,4,1.68,0.420000,2009-12-03,2009-12-03,1,1,4.000000,0.000000,4.000000,0.0,0.0,0.0,1,28.000000,56.000000,56.000000
3,10120,DOGGY RUBBER,664,142.74,0.240137,2009-12-01,2011-12-04,73,2,10.375000,-0.003606,0.904632,-8320.0,30.0,-8350.0,734,6.332425,12.664850,8362.664850
4,10125,MINI FUNKY DESIGN TAPES,2103,1715.78,0.930636,2009-12-01,2011-12-09,167,6,16.959677,0.000000,2.845737,2151.0,0.0,2151.0,739,19.920162,39.840325,-2111.159675

In [15]:
inventory_df["Stock_Status"] = "Optimal"

inventory_df.loc[
    inventory_df["Net_Quantity"]
    < inventory_df["Reorder_Point"],
    "Stock_Status"
] = "Reorder Required"

inventory_df.loc[
    inventory_df["Net_Quantity"]
    >
    inventory_df["Reorder_Point"] * 1.5,
    "Stock_Status"
] = "Overstock"

inventory_df["Stock_Status"].value_counts()

Stock_Status
Overstock           4456
Reorder Required     434
Optimal               27
Name: count, dtype: int64

In [16]:
inventory_df["Recommendation"] = (
    inventory_df["Stock_Status"]
)

inventory_df.loc[
    inventory_df["Stock_Status"]
    == "Reorder Required",
    "Recommendation"
] = "Reorder Immediately"

inventory_df.loc[
    inventory_df["Stock_Status"]
    == "Optimal",
    "Recommendation"
] = "Maintain Current Stock"

inventory_df.loc[
    inventory_df["Stock_Status"]
    == "Overstock",
    "Recommendation"
] = "Reduce Future Orders"

inventory_df.head()

,StockCode,Description,Total_Quantity_Sold,Total_Revenue,Avg_Price,First_Sale_Date,Last_Sale_Date,Num_Orders,Num_Countries_Sold,SKU_Demand_Velocity,...,Average_Daily_Demand,Gross_Quantity,Return_Quantity,Net_Quantity,Product_Lifespan_Days,Safety_Stock,Reorder_Point,Inventory_Gap,Stock_Status,Recommendation
0,10002,INFLATABLE POLITICAL GLOBE,8671,6942.26,0.979155,2009-12-01,2011-04-18,362,12,38.537778,...,17.204365,9013.0,1223.0,7790.0,504,120.430556,240.861111,-7549.138889,Overstock,Reduce Future Orders
1,10080,GROOVY CACTUS INFLATABLE,315,129.29,0.505000,2009-12-02,2011-11-21,27,1,12.115385,...,0.437500,597.0,0.0,597.0,720,3.062500,6.125000,-590.875000,Overstock,Reduce Future Orders
2,10109,BENDY COLOUR PENCILS,4,1.68,0.420000,2009-12-03,2009-12-03,1,1,4.000000,...,4.000000,0.0,0.0,0.0,1,28.000000,56.000000,56.000000,Reorder Required,Reorder Immediately
3,10120,DOGGY RUBBER,664,142.74,0.240137,2009-12-01,2011-12-04,73,2,10.375000,...,0.904632,-8320.0,30.0,-8350.0,734,6.332425,12.664850,8362.664850,Reorder Required,Reorder Immediately
4,10125,MINI FUNKY DESIGN TAPES,2103,1715.78,0.930636,2009-12-01,2011-12-09,167,6,16.959677,...,2.845737,2151.0,0.0,2151.0,739,19.920162,39.840325,-2111.159675,Overstock,Reduce Future Orders

In [17]:
print(
    inventory_df["Stock_Status"]
    .value_counts()
)

Stock_Status
Overstock           4456
Reorder Required     434
Optimal               27
Name: count, dtype: int64

In [18]:
reorder_count = (
    inventory_df["Stock_Status"]
    == "Reorder Required"
).sum()

overstock_count = (
    inventory_df["Stock_Status"]
    == "Overstock"
).sum()

print(
    f"Reorder Required: {reorder_count}"
)

print(
    f"Overstock: {overstock_count}"
)

Reorder Required: 434
Overstock: 4456

In [19]:
inventory_output = inventory_df[
    [
        "StockCode",
        "Description",
        "Average_Daily_Demand",
        "Net_Quantity",
        "Safety_Stock",
        "Reorder_Point",
        "Inventory_Gap",
        "Stock_Status",
        "Recommendation"
    ]
]

inventory_output.to_csv(
    "../outputs/inventory_recommendations.csv",
    index=False
)

print(
    "inventory_recommendations.csv saved"
)

inventory_recommendations.csv saved

In [20]:
df["Inventory_Status"] = df["Inventory_Gap"].apply(
    lambda x: "Restock Required"
    if x > 0
    else "Sufficient Stock"
)

df[
    [
        "StockCode",
        "Net_Quantity",
        "Reorder_Point",
        "Inventory_Gap",
        "Inventory_Status"
    ]
].head()

KeyError: 'Inventory_Gap'

In [21]:
print(df.columns.tolist())

['StockCode', 'Description', 'Total_Quantity_Sold', 'Total_Revenue', 'Avg_Price', 'First_Sale_Date', 'Last_Sale_Date', 'Num_Orders', 'Num_Countries_Sold', 'SKU_Demand_Velocity', 'Return_Rate', 'Average_Daily_Demand', 'Gross_Quantity', 'Return_Quantity', 'Net_Quantity', 'Product_Lifespan_Days']

In [22]:
df["Safety_Stock"] = df["Average_Daily_Demand"] * 7

df["Reorder_Point"] = df["Average_Daily_Demand"] * 14

df["Inventory_Gap"] = (
    df["Reorder_Point"]
    - df["Net_Quantity"]
)

df.head()

,StockCode,Description,Total_Quantity_Sold,Total_Revenue,Avg_Price,First_Sale_Date,Last_Sale_Date,Num_Orders,Num_Countries_Sold,SKU_Demand_Velocity,Return_Rate,Average_Daily_Demand,Gross_Quantity,Return_Quantity,Net_Quantity,Product_Lifespan_Days,Safety_Stock,Reorder_Point,Inventory_Gap
0,10002,INFLATABLE POLITICAL GLOBE,8671,6942.26,0.979155,2009-12-01,2011-04-18,362,12,38.537778,0.135693,17.204365,9013.0,1223.0,7790.0,504,120.430556,240.861111,-7549.138889
1,10080,GROOVY CACTUS INFLATABLE,315,129.29,0.505000,2009-12-02,2011-11-21,27,1,12.115385,0.000000,0.437500,597.0,0.0,597.0,720,3.062500,6.125000,-590.875000
2,10109,BENDY COLOUR PENCILS,4,1.68,0.420000,2009-12-03,2009-12-03,1,1,4.000000,0.000000,4.000000,0.0,0.0,0.0,1,28.000000,56.000000,56.000000
3,10120,DOGGY RUBBER,664,142.74,0.240137,2009-12-01,2011-12-04,73,2,10.375000,-0.003606,0.904632,-8320.0,30.0,-8350.0,734,6.332425,12.664850,8362.664850
4,10125,MINI FUNKY DESIGN TAPES,2103,1715.78,0.930636,2009-12-01,2011-12-09,167,6,16.959677,0.000000,2.845737,2151.0,0.0,2151.0,739,19.920162,39.840325,-2111.159675

In [23]:
print(df.columns.tolist())

['StockCode', 'Description', 'Total_Quantity_Sold', 'Total_Revenue', 'Avg_Price', 'First_Sale_Date', 'Last_Sale_Date', 'Num_Orders', 'Num_Countries_Sold', 'SKU_Demand_Velocity', 'Return_Rate', 'Average_Daily_Demand', 'Gross_Quantity', 'Return_Quantity', 'Net_Quantity', 'Product_Lifespan_Days', 'Safety_Stock', 'Reorder_Point', 'Inventory_Gap']

In [24]:
df["Inventory_Status"] = df["Inventory_Gap"].apply(
    lambda x: "Restock Required"
    if x > 0
    else "Sufficient Stock"
)

df[
    [
        "StockCode",
        "Net_Quantity",
        "Reorder_Point",
        "Inventory_Gap",
        "Inventory_Status"
    ]
].head()

  StockCode  Net_Quantity  Reorder_Point  Inventory_Gap  Inventory_Status
0     10002        7790.0     240.861111   -7549.138889  Sufficient Stock
1     10080         597.0       6.125000    -590.875000  Sufficient Stock
2     10109           0.0      56.000000      56.000000  Restock Required
3     10120       -8350.0      12.664850    8362.664850  Restock Required
4     10125        2151.0      39.840325   -2111.159675  Sufficient Stock

In [25]:
df["Inventory_Status"].value_counts()

Inventory_Status
Sufficient Stock    4483
Restock Required     434
Name: count, dtype: int64

In [27]:
df.to_csv(
    "../outputs/inventory_recommendations.csv",
    index=False
)

print("Inventory Export Complete")

Inventory Export Complete

In [28]:
df["Recommendation"] = df["Inventory_Status"].apply(
    lambda x: "Order Immediately"
    if x == "Restock Required"
    else "Monitor Stock"
)

df.head()

,StockCode,Description,Total_Quantity_Sold,Total_Revenue,Avg_Price,First_Sale_Date,Last_Sale_Date,Num_Orders,Num_Countries_Sold,SKU_Demand_Velocity,...,Average_Daily_Demand,Gross_Quantity,Return_Quantity,Net_Quantity,Product_Lifespan_Days,Safety_Stock,Reorder_Point,Inventory_Gap,Inventory_Status,Recommendation
0,10002,INFLATABLE POLITICAL GLOBE,8671,6942.26,0.979155,2009-12-01,2011-04-18,362,12,38.537778,...,17.204365,9013.0,1223.0,7790.0,504,120.430556,240.861111,-7549.138889,Sufficient Stock,Monitor Stock
1,10080,GROOVY CACTUS INFLATABLE,315,129.29,0.505000,2009-12-02,2011-11-21,27,1,12.115385,...,0.437500,597.0,0.0,597.0,720,3.062500,6.125000,-590.875000,Sufficient Stock,Monitor Stock
2,10109,BENDY COLOUR PENCILS,4,1.68,0.420000,2009-12-03,2009-12-03,1,1,4.000000,...,4.000000,0.0,0.0,0.0,1,28.000000,56.000000,56.000000,Restock Required,Order Immediately
3,10120,DOGGY RUBBER,664,142.74,0.240137,2009-12-01,2011-12-04,73,2,10.375000,...,0.904632,-8320.0,30.0,-8350.0,734,6.332425,12.664850,8362.664850,Restock Required,Order Immediately
4,10125,MINI FUNKY DESIGN TAPES,2103,1715.78,0.930636,2009-12-01,2011-12-09,167,6,16.959677,...,2.845737,2151.0,0.0,2151.0,739,19.920162,39.840325,-2111.159675,Sufficient Stock,Monitor Stock

In [29]:
df.to_csv(
    "../outputs/inventory_recommendations.csv",
    index=False
)